### ISSUE TITLE
Error inflating class MvxRecyclerView

### ISSUE THREAD

**Issue by esskar** [kjeremy/MvxAndroid.Support.V7.AppCompat#2]
I am trying to add the MvxRecyclerView to my views, but the inflating fails.
How do i have to reference it?

**Comment by xleon** [comment]
Try using the full name space in your layout axml file instead of just "MvxRecyclerView":
"MvxAndroid.Support.V7.AppCompat.Views.MvxRecyclerView"

**Comment by esskar** [comment]
thanks.
